name: BlueBamboo
version: 1.0
main: net.bbforest.bluebamboo.EKE
api-version: 1.18

commands:
  bluebamboo:
    aliases: [bb, 파란대나무, 파대]
    description: 플러그인 기본 명령어
    usage: /<command> <help|reload>
  broadcast:
    aliases: [bc, bbc, 공지]
    description: 알립니다!
    usage: /<command> <할말>
  inventory:
    aliases: [inv, inven, binv, 인벤]
    description: 인벤토리 스냅샷을 저장합니다.
    usage: /<command> <save|view> [닉네임] [파일명]